services:
  web:
    image: akh2100/midterm-app:v1
    container_name: midterm-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/products_db
      - PORT=3000
    depends_on:
      - database
    volumes:
      - uploads_data:/usr/src/app/public/uploads
    networks:
      - app-network

  database:
    image: mongo:7.0
    container_name: midterm-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:
  uploads_data:

networks:
  app-network:
    driver: bridge